### PR TITLE
Use rescue_exception from Rack::FiberPool to show sinatra's printer.

### PR DESCRIPTION
**Pull request by francois2metz**
We have added support of the new rescue_exception params of Rack::FiberPool. 

When an exception occurs after the fiber has been resumed at least once, we have no way to catch the exception. Now we are showing the default error page of sinatra if show_exceptions is enabled.

See mperham/rack-fiber_pool#11.

### CODE REVIEW

**Comment by kyledrake** [comment]
This is great! Apologies for the delay, I will merge this now. Thank you!

**Comment by kyledrake** [comment]
As soon as I get into the office and test this, I will push a new version.

**Comment by francois2metz** [comment]
Thanks!

**Comment by kyledrake** [comment]
@francois2metz, I was curious as to what was going on here: https://github.com/kyledrake/sinatra-synchrony/commit/c23213e05684cf126e4e28ac76590d51d8c6d2c9#L0R24

What scenario would return a status of 500 with an empty string ([500, {}, ""])? Is that caught by the Rack::FiberPool change and ignored, or does something need to be implemented there?

**Comment by francois2metz** [comment]
We return an empty 500 error in production typically. We could probably do a better error handling in production.

**Pull request merged**
